Chore/updates
mysense-ai/ServerlessPlugin-SSMPublish pull request #139
Opened 2022-10-31 19:16 UTC by ColdFire87

- update npm modules & node engine versions

2022-11-08 14:03 UTC, mikesalmon-mysense commented on .travis.yml
> -      script: yarn install --frozen-lockfile
@ColdFire87 - any reason not to also use "frozen-lockfile" here to ensure it's not out of sync?

2022-11-14 13:57 UTC, mikesalmon-mysense commented
Hey @ColdFire87 , for this, I also noticed travis ci failed, but due to auth issue with `fundingcircle.jfrog.io` - was that intentional to update `yarn.lock` references?

2022-12-01 11:52 UTC, mikesalmon-mysense requested changes
Multiple references to `fundingcircle.jfrog.io` in `yarn.lock` file - was that intentional?

2022-12-14 21:52 UTC, ColdFire87 commented
Hmm... I think it's because I did it from my work laptop, and I have the npm registry setup to use `fundingcircle.jfrog.io`.
I will reinstall the deps from my personal laptop and push the change.

2023-01-13 11:17 UTC, closed without merging